import"./assets/theme-BdXRRVLI.js";import{I as u,E as a,f as y,B as r,c as g}from"./assets/stars-ZdAbMgea.js";import"./assets/vendor-DDD7fsZd.js";const m=document.getElementById("movieDetailModal"),i=document.getElementById("detailPoster"),p=document.getElementById("detailTitle"),h=document.getElementById("detailVotes"),I=document.getElementById("detailPopularity"),v=document.getElementById("detailGenres"),E=document.getElementById("detailOverview"),f=document.getElementById("closeDetailModal");function b(e,t){try{i.src=`${u}${a.IMG_W500}${e.poster_path}`,i.alt=e.title,p.textContent=e.title,h.textContent=`${e.vote_average} / ${e.vote_count}`,I.textContent=Math.floor(e.popularity);const n=e.genre_ids||(e.genres?e.genres.map(o=>o.id):[]);(!t||Object.keys(t).length===0)&&(console.warn("Genre map boş veya tanımsız! Genre verileri henüz yüklenmemiş."),v.textContent="Unknown"),E.textContent=e.overview||"No description available.",m.classList.add("active")}catch(n){console.error("openMovieDetailModal hatası:",n)}}f.addEventListener("click",()=>{m.classList.remove("active")});async function B(){const t=await(await y(r,a.POPULAR_MOVIES)).results;let n=0;const o=document.querySelector(".hero-container");d(t[n]),setInterval(()=>{o.style.opacity="0",setTimeout(()=>{n=(n+1)%t.length,d(t[n]),o.style.opacity="1"},500)},5e3)}function d(e){const t=document.querySelector(".hero-container");console.log(e);const n=`${u}${a.IMG_W1280}${e.backdrop_path}`;t.style.backgroundImage=`url('${n}')`;const o=g(e.vote_average);t.innerHTML=`
<div class="hero-content">
  <h1 class="hero-title">${e.title}</h1>
  <div class="hero-rating">${o}</div>
  <p class="hero-description">${e.overview}</p>
  <div class="hero-buttons">
    <button class="watch-trailer-btn">Watch trailer</button>
    <button class="more-details-btn">More details</button>
  </div>
</div>
`,document.querySelector(".watch-trailer-btn").addEventListener("click",()=>$(e.id)),document.querySelector(".more-details-btn").addEventListener("click",()=>b(e))}async function w(){const t=await(await fetch(`${r}/genre/movie/list?api_key=${API_KEY}&language=en-US`)).json();M(t.genres)}function M(e){const t=document.getElementById("category");t&&(t.innerHTML=e.map(n=>`
        <div class="category-card">${n.name}</div>
      `).join(""))}B();w();async function $(e){const o=(await(await fetch(`${r}/movie/${e}/videos?api_key=52238d7fab5c2c01b99e751619dd16ec&language=en-US`)).json()).results.find(l=>l.type==="Trailer"&&l.site==="YouTube"),s=document.getElementById("trailerIframe"),c=document.getElementById("trailerModal");o?(s.src=`https://www.youtube.com/embed/${o.key}`,c.style.display="block"):alert("Trailer bulunamadı.")}document.getElementById("closeTrailer").addEventListener("click",()=>{const e=document.getElementById("trailerModal"),t=document.getElementById("trailerIframe");e.style.display="none",t.src=""});
//# sourceMappingURL=catalog.js.map
