import"./assets/theme-C3VdtH2B.js";import{I as u,E as c,a as y,B as l}from"./assets/fetchMovies-DXPj_YoO.js";import"./assets/vendor-DDD7fsZd.js";function p(e){const t=Math.round(e)/2,n=Math.floor(t),a=t%1>=.5?1:0,r=5-n-a;let s="";for(let o=0;o<n;o++)s+='<span class="star">★</span>';a&&(s+='<span class="half-star">⯨</span>');for(let o=0;o<r;o++)s+='<span class="star-empty">☆</span>';return s}const m=document.getElementById("movieDetailModal"),i=document.getElementById("detailPoster"),g=document.getElementById("detailTitle"),h=document.getElementById("detailVotes"),f=document.getElementById("detailPopularity"),I=document.getElementById("detailGenres"),v=document.getElementById("detailOverview"),E=document.getElementById("closeDetailModal");function b(e,t){try{i.src=`${u}${c.IMG_W500}${e.poster_path}`,i.alt=e.title,g.textContent=e.title,h.textContent=`${e.vote_average} / ${e.vote_count}`,f.textContent=Math.floor(e.popularity);const n=e.genre_ids||(e.genres?e.genres.map(a=>a.id):[]);(!t||Object.keys(t).length===0)&&(console.warn("Genre map boş veya tanımsız! Genre verileri henüz yüklenmemiş."),I.textContent="Unknown"),v.textContent=e.overview||"No description available.",m.classList.add("active")}catch(n){console.error("openMovieDetailModal hatası:",n)}}E.addEventListener("click",()=>{m.classList.remove("active")});async function B(){const t=await(await y(l,c.POPULAR_MOVIES)).results;let n=0;const a=document.querySelector(".hero-container");d(t[n]),setInterval(()=>{a.style.opacity="0",setTimeout(()=>{n=(n+1)%t.length,d(t[n]),a.style.opacity="1"},500)},5e3)}function d(e){const t=document.querySelector(".hero-container");console.log(e);const n=`${u}${c.IMG_W1280}${e.backdrop_path}`;t.style.backgroundImage=`url('${n}')`;const a=p(e.vote_average);t.innerHTML=`
<div class="hero-content">
  <h1 class="hero-title">${e.title}</h1>
  <div class="hero-rating">${a}</div>
  <p class="hero-description">${e.overview}</p>
  <div class="hero-buttons">
    <button class="watch-trailer-btn">Watch trailer</button>
    <button class="more-details-btn">More details</button>
  </div>
</div>
`,document.querySelector(".watch-trailer-btn").addEventListener("click",()=>$(e.id)),document.querySelector(".more-details-btn").addEventListener("click",()=>b(e))}async function M(){const t=await(await fetch(`${l}/genre/movie/list?api_key=${API_KEY}&language=en-US`)).json();w(t.genres)}function w(e){const t=document.getElementById("category");t&&(t.innerHTML=e.map(n=>`
        <div class="category-card">${n.name}</div>
      `).join(""))}B();M();async function $(e){const a=(await(await fetch(`${l}/movie/${e}/videos?api_key=52238d7fab5c2c01b99e751619dd16ec&language=en-US`)).json()).results.find(o=>o.type==="Trailer"&&o.site==="YouTube"),r=document.getElementById("trailerIframe"),s=document.getElementById("trailerModal");a?(r.src=`https://www.youtube.com/embed/${a.key}`,s.style.display="block"):alert("Trailer bulunamadı.")}document.getElementById("closeTrailer").addEventListener("click",()=>{const e=document.getElementById("trailerModal"),t=document.getElementById("trailerIframe");e.style.display="none",t.src=""});
//# sourceMappingURL=catalog.js.map
